MERGE INTO APP.DWD_ORDER t
USING (
    SELECT ID, AMOUNT
    FROM APP.ODS_ORDER
) s
ON (t.ORDER_ID = s.ID)
WHEN MATCHED THEN
    UPDATE SET t.AMOUNT = s.AMOUNT
WHEN NOT MATCHED THEN
    INSERT (ORDER_ID, AMOUNT)
    VALUES (s.ID, s.AMOUNT);
